In [1]:
import tensorflow as tf
# import tensorflow

In [2]:
sess = tf.InteractiveSession()  # then we can simplify the option of sess.run()

i_matrix = tf.eye(5)
print(i_matrix.eval())


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
x = tf.Variable(tf.eye(10))
x.initializer.run()     # sess.run(x.initializer)
print(x.eval())
# Evaluate the Variable and print the result

Instructions for updating:
Colocations handled automatically by placer.


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [4]:
a = tf.Variable(tf.random_normal([5, 10]))
a.initializer.run()

product = tf.matmul(a, x)   # multiply two matrices
print(product.eval())   # eval = evaluate = calculate = sess.run(fetches, feed_dict...)

[[ 1.1268214  -0.07541788  0.13734724 -0.06703051 -0.02726404  0.58679825
   0.07476194 -0.7182946  -0.37819043  0.8962354 ]
 [-0.36443144  2.3556945  -0.9066026  -0.38138536  0.3033934  -0.8624864
  -0.9234215  -0.9251427  -0.37474683  0.9477685 ]
 [ 0.5856476  -0.6517978   0.25672868 -1.2145989  -0.41023442  0.7085469
  -0.57204473  1.7072134  -0.38418895  1.1739513 ]
 [-0.7292974   0.28294432  0.47209135 -0.18394503 -0.42708108 -1.2207555
  -0.25989774 -0.72766787 -0.65032464  1.3251866 ]
 [ 1.035721    0.68439525  1.7559799   1.3812845   1.6872468   1.5042131
  -0.14574537  1.5438229   0.17041889 -2.0911975 ]]


In [7]:
# create a random matrix of 1s and 0s, size 5x10
b = tf.Variable(tf.random_uniform([5, 10], 0, 2, dtype=tf.int32))
b.initializer.run()
print(b.eval())

b_new = tf.cast(b, dtype=tf.float32)

[[0 0 1 0 1 1 0 0 1 1]
 [1 0 0 1 1 1 0 1 1 1]
 [0 1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 0 1 0 0]
 [1 1 1 0 0 0 1 0 1 1]]


In [8]:
t_sum = tf.add(product, b_new)
t_sub = product - b_new

print("A*X _b \n", t_sum.eval())
print("A*X - b \n", t_sub.eval())

A*X _b 
 [[ 1.1268214  -0.07541788  1.1373472  -0.06703051  0.97273594  1.5867982
   0.07476194 -0.7182946   0.6218096   1.8962355 ]
 [ 0.63556856  2.3556945  -0.9066026   0.6186147   1.3033934   0.13751358
  -0.9234215   0.07485729  0.6252532   1.9477684 ]
 [ 0.5856476   0.34820223  0.25672868 -1.2145989  -0.41023442  0.7085469
  -0.57204473  1.7072134  -0.38418895  2.1739511 ]
 [ 0.2707026   1.2829443   1.4720913   0.81605494  0.5729189  -0.22075546
  -0.25989774  0.27233213 -0.65032464  1.3251866 ]
 [ 2.0357208   1.6843953   2.75598     1.3812845   1.6872468   1.5042131
   0.8542546   1.5438229   1.1704189  -1.0911975 ]]
A*X - b 
 [[ 1.1268214  -0.07541788 -0.8626528  -0.06703051 -1.027264   -0.41320175
   0.07476194 -0.7182946  -1.3781904  -0.10376459]
 [-1.3644314   2.3556945  -0.9066026  -1.3813853  -0.69660664 -1.8624864
  -0.9234215  -1.9251428  -1.3747468  -0.05223149]
 [ 0.5856476  -1.6517978   0.25672868 -1.2145989  -0.41023442  0.7085469
  -0.57204473  1.7072134  -0.3841889

In [9]:
# some other option
a = tf.Variable(tf.random_normal([4, 5], stddev=2))
b = tf.Variable(tf.random_normal([4, 5], stddev=2))

# elements wise multiplication
A = a*b

# multiplication with scalar 2
B = tf.scalar_mul(2, A)

# elementwise division, its result is
C = tf.div(a, b)

# element wise remainder of division
D = tf.mod(a, b)

init_op = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init_op)

writer = tf.summary.FileWriter('graphs', sess.graph)
a, b, A_R, B_R, C_R, D_R = sess.run([a, b, A, B, C, D])

print("a:\n", a, "\n b:\n", b, "\n a*b\n",
      A_R, "\n 2*a*b: \n", B_R, "\n a/b: \n", C_R, "\n a%b: \n", D_R)

writer.close()
sess.close()



Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


a:
 [[-1.073663    0.42696834  2.4697654   1.0959783   1.1477964 ]
 [-1.0268139   0.28909335  0.28138655 -2.3447895  -1.2895677 ]
 [ 0.5509032  -1.3226422   5.045516    0.18865643 -0.42369422]
 [-2.8499188   1.8328598   0.42222095  1.2241217  -5.2408586 ]] 
 b:
 [[-0.6941402  -1.6706158  -1.4549235   1.8060231   0.51780623]
 [-0.07345588 -0.51726574  1.0862154  -1.1075462  -0.8979824 ]
 [-1.118018    2.703206    0.33025423  0.01212805 -0.519491  ]
 [-1.2906011   3.4052896   3.100042    1.2004067  -0.54431915]] 
 a*b
 [[ 7.4527264e-01 -7.1330005e-01 -3.5933199e+00  1.9793621e+00
   5.9433615e-01]
 [ 7.5425513e-02 -1.4953808e-01  3.0564639e-01  2.5969627e+00
   1.1580092e+00]
 [-6.1591971e-01 -3.5753744e+00  1.6663030e+00  2.2880347e-03
   2.2010535e-01]
 [ 3.6781085e+00  6.2414184e+00  1.3089027e+00  1.4694438e+00
   2.8526998e+00]] 
 2*a*b: 
 [[ 1.4905453e+00 -1.4266001e+00 -7.1866398e+00  3.9587243e+00
   1.1886723e+00]
 [ 1.5085103e-01 -2.9907617e-01  6.1129278e-01  5.1939254e+00
   